version: '3.1'

services:

  db:
    container_name: bsc_indexer_db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mypasswd"
      MYSQL_DATABASE: bsc

  phpmyadmin:
    container_name: bsc_indexer_pma
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"